USE [MSSQLDB]
GO

/****** Object:  Table [dbo].[Clients]    Script Date: 11.04.2024 18:14:28 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Clients](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Surname] [nvarchar](25) NOT NULL,
	[FirstName] [nvarchar](25) NOT NULL,
	[Patronymic] [nvarchar](25) NOT NULL,
	[TelephoneNumber] [nvarchar](25) NULL,
	[Email] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK__tmp_ms_x__3214EC07C28D16C5] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UQ__tmp_ms_x__A9D10534A5CEAD8B] UNIQUE NONCLUSTERED 
(
	[Email] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO